name: CI/CD Pipeline

on:
  push:
    branches: [development, main]
  pull_request:
    branches: [development, main]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linting
      run: npm run lint
    
    - name: Check formatting
      run: npm run format:check
    
    - name: Run type checking
      run: npm run type-check
    
    - name: Run tests
      run: npm test
    
    - name: Build project
      run: npm run build
    
    - name: Deploy to Vercel (on merge to development)
      if: github.ref == 'refs/heads/development' && github.event_name == 'push'
      run: |
        echo "Deploying to Vercel..."
        # Vercel deployment will be handled by Vercel's GitHub integration 